import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import NextTopLoader from "nextjs-toploader";

// import TwScreenInfo from "@/components/custom/TwScreenInfo";

const silver = localFont({
  src: "./Silver-Queen.otf",
  variable: "--font-silver",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${silver.variable} antialiased`}
      >
        <NextTopLoader height={3} color="#3b82f6" />

        <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        {children}
        <Analytics />
        <SpeedInsights />
        <Toaster />

        {/* <TwScreenInfo /> */}
      </body>
    </html>
  );
}
