import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
// import TwScreenInfo from "@/components/custom/TwScreenInfo";

const silver = localFont({
  src: "./fonts/Silver-Queen.otf",
  variable: "--font-silver",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${silver.variable} antialiased`}
      >
        {children}
        <Analytics />
        <SpeedInsights />
        {/* <TwScreenInfo /> */}
      </body>
    </html>
  );
}
